name: Unit tests

on: push

jobs:
  job1:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from the repository
        uses: actions/checkout@v2

      - name: Python environment configuration
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run : | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: python -m unittest